config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :bets
      resources :competitions
      resources :competitions_users
      resources :events
      resources :games
      resources :teams

      root to: "users#index"
    end
  resources :bets

  resources :competitions

  resources :events

  resources :games

  resources :teams

  get 'competitions/:id/results' => 'competitions#results', :as => :competition_results
  get 'competitions/:id/join' => 'competitions#join', :as => :competition_join
  post 'competitions/:id/add_user' => 'competitions#add_user', :as => :competition_add_user
  delete 'competitions/:id/remove_user' => 'competitions#remove_user', :as => :competition_remove_user
  get 'games/:id/all_bets/:idc' => 'games#all_bets', :as => :games_all_bets
  get 'competition/:id/all_winner_bets/:idc' => 'competitions#all_winner_bets', :as => :competition_all_winner_bets

authenticated :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "visitors#index", :as => "authenticated_root"
end

devise_scope :user do
  root to: 'devise/sessions#new'
end
  devise_for :users	
  
  resources :users
end

app/models/competition.rb
class Competition < ActiveRecord::Base
  belongs_to :event
  belongs_to :creator, class_name: "User"
  has_many :bets
  has_many :competitions_users, class_name: "CompetitionsUsers"
  has_many :users, :through => :competitions_users
  
  accepts_nested_attributes_for :competitions_users

  validates :event_id, presence: true

  scope :open, lambda { ||
    where(is_open: true)
  }

  def points_for_user(user)   
    score = 0
  	user.bets.where(:competition => self).each do |bet|
  		score += (bet.points_earned!=nil ? bet.points_earned : 0)
  	end
    return score
  end

  def winner_bet_for_user(user) 
    user.bets.where(:competition => self, :game => nil).take
  end
  
  def is_winner_bet_scored(user)
    user.bets.where(:competition => self, :game => nil, 'points_earned' => 10).take
  end

  def all_winner_bets
    @wBets = []
    if event.winner_bet_deadline_time < Time.zone.now
      users.each do |usr|
        @wBets << winner_bet_for_user(usr)
      end
    end
    @wBets
  end

  def user_belongs_to(user)
    competitions_users.exists?(:user_id => user.id)
  end

  def get_scoreboard
    scores = Hash.new
    users.each do |usr|
      scores[usr] = points_for_user(usr)
    end
    return scores.sort_by { |usr, score| score}.reverse
  end
end

app/controllers/admin/competitions_controller.rb
module Admin
  class CompetitionsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_competition, only: [:show, :edit, :update, :destroy, :results, :add_user]

  respond_to :html

  def index
    @competitions = Competition.open
    respond_with(@competitions)
  end

  def show
    @my_bets = Bet.for_user_and_competition(current_user, @competition)
    @winner_bet = @competition.winner_bet_for_user(current_user)
    @is_winner_bet_score = @competition.is_winner_bet_scored(current_user)
    @winner_bet_deadline_time = @competition.event.winner_bet_deadline_time
    @winner_bet_deadline_str = @competition.event.winner_bet_deadline_str
    @live_games = @competition.event.games.live
    @completed_games = @competition.event.games.completed
    if @winner_bet.nil?

    else
      @competition.event.all_teams.each do |team|
        if team.id == @winner_bet.advancing_team
          @team = team
        end
      end
    end
    respond_with(@competition)
  end

  def all_winner_bets
    @competition = Competition.find params[:idc]
    @bets = @competition.all_winner_bets
    respond_to do |format|
      format.js 
    end
  end

  def results
    @scoreboard = @competition.get_scoreboard
    respond_with(@scoreboard)
  end

  def join
    @assoc = CompetitionsUsers.create(user: current_user, competition: @competition)
    flash[:notice] = 'Dolaczyles do rozgrywek' if (@assoc.save)
    redirect_to competition_path(@competition)
    #respond_with(@competition)
  end

  def add_user
    @usr = User.find params[:usr]
    @assoc = CompetitionsUsers.create(user: @usr, competition: @competition)
    flash[:notice] = ('Uzytkownik '+@usr.name+' zostal pomyślnie dodany do rozgrywek') if (@assoc.save)
    redirect_to edit_competition_path(@competition)
  end

  def remove_user
    @usr = User.find params[:usr]
    CompetitionsUsers.where(user: @usr).first.destroy
    flash[:notice] = ('Uzytkownik '+@usr.name+' zostal usunięty z rozgrywek') 
    redirect_to edit_competition_path(@competition)
  end                                                                                                                              

  def new
    @competition = Competition.new
    respond_with(@competition)
  end

  def edit
    @candidates = User.where.not(id: @competition.users.ids)
  end

  def create
    @competition = Competition.new
    @competition.creator_id = current_user.id
    @competition.competitions_users.build(user: current_user)
    flash[:notice] = 'Competition was successfully created.' if (@competition.save)
    respond_with(@competition)
  end

  def update
    flash[:notice] = 'Competition was successfully updated.' if @competition.update(competition_params)
    respond_with(@competition)
  end

  def destroy
    @competition.destroy
    respond_with(@competition)
  end

  private
    def set_competition
      @competition = Competition.find(params[:id])
    end

    def competition_params
      params.require(:competition).permit(:event_id, :is_open, :usr)
    end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= simple_form_for(@competition) do |f| %>
  <%= f.error_notification %>

	<form class="form" action="index.html">
	<label for="competition_select"><%= t('choose_event')%></label>
	<select class="" name="competition[event_id]" id="competition_select">
		<option value="" disabled>Wybierz</option>
		<% Event.all.each do |event| %>
			<option value="<%= event.id %>" <%= @competition.event == event ? "selected" : ""%> ><%= event.name %></option>
		<% end %>
	</select>		
		<%= f.check_box :is_open, id:'is_open' %>
		<%= f.label t('is_open'), for:'is_open', id:'is_open' %>
		<p>
	    <%= link_to competitions_path, class: "btn btn-block waves-button waves-effect waves-light margin-no-top left-align" do %>
       		<%= t('back') %>
       	<% end %>
  		<button class="btn waves-effect waves-light right-align" type="submit" name="action"> <%= t('save') %>
			<i class="material-icons right">send</i>
		</button> 
	</p>
  	</form>
<% end %>

app/views/competitions/_show_as_card.html.erb
<div class="col s12 m6">
  <div class="card blue-grey darken-2 hoverable">
    <div class="card-content white-text">
      <span class="card-title"><b><%= competition.event.name%></b></span><span class="badge teal lighten-2 white-text"><%=  competition.users.count%> <%= t('competitors') %> </span>
       <div>
        <%= t('created_by') %>
        <% if current_user == competition.creator %>
          <%= t('you_created_by') %>
        <% else %>
         <%= link_to competition.creator.email, competition.creator %>
        <% end %>
        <span class="right-align grey-text"><h3> <b><%= competition.id %></b></h3></span>
      </div>
    </div>
    <div class="card-action">
     <% if competition.user_belongs_to(current_user) %>
      <%= link_to competition do %>
        <%= t('show_competition') %>
      <% end %>
      <% else %>
        <%= link_to t('join'), competition_join_path(competition) %>
      <% end %>            
    </div>         
  </div>
</div>

app/views/competitions/_winner_bets_list.html.erb
<ul class="collection with-header">
	<% if @bets.empty? == false %>
	<% @bets.each do |bett| %>
		<% if bett.nil? %>

		<% else %>
			<% if bett.points_earned == 10 %>
		    <li class="collection-item green white-text"><%= bett.owner.name %>
		    	<span class="secondary-content white-text"><%= (Team.find bett.advancing_team).name %></span></li>
		    <% else %>
		    <li class="collection-item"><%= bett.owner.name %>
		    	<span class="secondary-content"><%= (Team.find bett.advancing_team).name %></span></li>		    
		    <% end %>
	    <% end %>
    <% end %>
	</ul>
	<% else %>
	</ul>
	<div class="center">
		<h5><%= t('none') %></h5>
	</div>
<% end %>

app/views/competitions/all_winner_bets.js.erb
$("#modalContent").html("<%= escape_javascript(render partial: 'winner_bets_list', locals: { bets: @bets } ) %>"); 
$('#allBetsModal').openModal();

app/views/competitions/edit.html.erb
<% content_for :welcome do %>
	<%= t('competition') %> <%= @competition.id %> 
<% end %>

<div class="row">
  	<div class="col s6">
	<%= render 'form' %>
	</div>
	<div class="col s6">
		<b>Atkualni uczestnicy:</b>
		<table class="highlight">
        	<thead>
          	<tr>
              <th data-field="id">Nazwa</th>
              <th data-field="name">E-mail</th>			           
          	</tr>
        	</thead>
        <tbody>        
		<% @competition.users.each do |user| %>
		   <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
			<td><%= link_to(t("X"), competition_remove_user_path(:usr => user), :data => { :confirm => "Jesteś pewien?" }, :method => :delete, :class => 'waves-effect waves-red btn red') %>
          </tr>		
		<% end %>
		</tbody>
	</table>
	<p>
		<b>Dodaj uczestnika:</b>
	</p>
	<p>
		<%= simple_form_for @competition, :url => competition_add_user_path, :method => :post do |f| %>

		<form class="form" action="index.html">		
		<select class="" name="usr" id="usr_select">
		<option value="" disabled>Wybierz</option>
			<% @candidates.each do |usr| %>
			<option value="<%= usr.id %>"><%= usr.name %> (<%= usr.email%>)</option>
		<% end %>
			</select>
		</p>
			<button class="btn waves-effect waves-light right-align" type="submit" name="action">
				Dodaj
			</button> 			 
			</form>
		<% end %>
	</div>
</div>

app/views/competitions/index.html.erb
<% content_for :welcome do %>
  <%= t('open_competitions') %>
<% end %>
<p class="flow-text">Rozgrywki publiczne, do których każdy może dołączyć:</p>
  <div class="row">
  	<% if @competitions.empty? %>
  	<div class="col s12 center">
  		<%= render partial: "layouts/empty" %>
  	</div>
  	<% else %>
		<% @competitions.each do |cp| %>
		    <%= render partial: "competitions/show_as_card", locals: {competition: cp} %>
		<% end %>
    <% end %>
  </div>

<br>
<div class="row">
	<div class="col s12 center">
	<% if can? :create, Competition %>		
		<br>
  		<%= link_to new_competition_path, :class => "waves-effect waves-light btn center amber" do %>
		<%= t('new_competition') %>
  		<i class="material-icons left">add</i>
  		<% end %>
  	<% else if @competitions.empty? %>
  	<h6 class="gray-text">
  		<%= t('no_competition') %>
  	</h6>
    <% end %>
	<% end %>
	</div>
</div>

app/views/competitions/new.html.erb
<% content_for :welcome do %>
  <%= t('new_competition') %>
<% end %>

<%= render 'form' %>

app/views/competitions/results.html.erb
<% content_for :welcome do %>
  <%= link_to @competition.event.name, @competition %>
<% end %>


  <table class="striped">
    <thead>
      <tr>
          <th data-field="id"><%= t('position')%></th>
          <th data-field="name"><%= t('user')%></th>
          <th data-field="price"><%= t('score')%></th>
      </tr>
    </thead>

    <tbody>
    <% @scoreboard.each_with_index do |usr_and_score,index| %>
      <tr class="<%= index==0 ? 'green-text' : '' %>">
        <td>
          <%= index != 0 && @scoreboard[index-1][1] == @scoreboard[index][1] ? '' : index+1 %>
        </td>
        <td><%= usr_and_score[0].name %></td>
        <td><b><%= usr_and_score[1] %></b></td>
      </tr>
 	  <% end %>    
    </tbody>
  </table>

<!--<ul class="collection with-header" id="results">
        <li class="collection-header"><h4><%= t('results') %> </h4></li>
  <% @scoreboard.each_with_index do |usr_and_score,index| %>
	<li class="collection-item <%= index==0 ? 'green-text' : '' %><%= index==(@scoreboard.count-1) ? 'red-text' : '' %> "><div><b><%= index+1 %></b> | <%= usr_and_score[0].name %> (<%= usr_and_score[0].email %>)
		<span class="secondary-content"><%= usr_and_score[1] %></span></div></li>
  <% end %>
</ul> -->

<p>
	<div class="row">
	 <div class="col s2 offset-s10 back-button">
	 <%= link_to @competition, class: 'btn waves-effect waves-light' do %>
            <%= t('back') %>
          <% end %>
	</div>
    </div>
</p>

app/views/competitions/show.html.erb
<% content_for :welcome do %>
  <%= @competition.event.name %>
  <% if current_user==@competition.creator %>
     <%= link_to edit_competition_path(@competition) do %>
      <i class="material-icons black-text">settings</i>
     <% end %>
  <% end %>
<% end %>

<% content_for :left_menu do %>
  <li>
    <%= link_to 'Wyniki', competition_results_path(@competition) %>
  </li>
<% end %> 

<ul class="collapsible" data-collapsible="accordion">
  <li>
    <div class="collapsible-header"><i class="material-icons">info</i>Zasady rozgrywek</div>
    <div class="collapsible-body">
      <p>
        <%= t('zasady') %>
      </p>
      <p>
        <%= t('zasady2') %> <span><i class="material-icons">view_list</i></span>  
      </p>
      <p>
      <b class="red-text">UWAGA!</b> Liczy się wyłącznie wynik w <b>regulaminowym</b> czasie gry! (bez ew. dogrywki i karnych).
    </p>
    </div>
  </li>
</ul>

<div class="row">
<div class="col s12" id="mybets">
    <!-- "przyczepiony" zakład na zwycięzcę-->
      <div class="section">
      <div class="row hoverable winner-row card-panel teal lighten-5">
      <div class="winner-bet-title">
        <p>
          <span class="title"><b><%= t('winner_bet') %></b>
          </span>
        </p>
      </div>
      <div class="winner-bet-container">
        <form id="winner-bet-form" class="form-inline">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
          <input type="hidden" name="bet[competition_id]" value="<%= params['id'] %>" />
          <input type="hidden" name="bet[bet_id]" value="<%= @winner_bet.blank? ? "" : @winner_bet.id %>">
          <input type="hidden" name="bet[home_score]" value="" />
          <input type="hidden" name="bet[away_score]" value="" />
          <input type="hidden" name="team-name" value="<%= @team.blank? ? "" : @team.name %>" />
          <input type="hidden" name="team-id" value="<%= @team.blank? ? "" : @team.id %>" />    
          <input type="hidden" name="team-flag" value="<%= @team.blank? ? "" : @team.flag.url(:tiny) %>" />
          <input type="hidden" name="deadline" value="<%= @competition.event.games.order('start_date ASC').first.start_date.strftime("%s000") %>">   
          <input type="hidden" name="is_editable" value="<%= @winner_bet_deadline_time.future? %>" />
          <input type="hidden" name="_method" value="post"/>
          <div id="winner-bet" class="row"></div>
          <% if @winner_bet_deadline_time.future? %>
           <div id="winner-deadline" class="winner-deadline"><%= @winner_bet_deadline_str %></div>
        <% end %>
        <script>
             var editWinnerHtml = '<div class="col s6"><select id="winner-dropdown" style="display: none" name="bet[advancing_team]" id="bet_select">' +
             '<option value="" disabled <%= @winner_bet.blank? ? "selected" : ""%>>Wybierz</option>' + 
             <% @competition.event.all_teams.each do |team| %>
            '<option value="<%= team.id %>" data-icon="<%= team.flag.url(:tiny) %>" class="circle left small" <%= (!@winner_bet.blank? && @winner_bet.advancing_team == team.id) ? "selected" : ""%> ><%= team.name %></option>' +
           <% end %>
         '</select><div class="bet-error-container"><span class="bet-error form-help form-help-msg text-red"></span></div></div><div class="bet-actions winner col s6"><a id="add-winner-button">ZAPISZ</a></div>';
         var displayAllBetsHtml = '<%= link_to competition_all_winner_bets_path(:id => @competition.id, :idc => @competition.id, :format => "js"), :remote => true do %><i class="material-icons">view_list</i><% end %>';
         var displayWinnerBetHtml = '<div class="display-winner-bet"><p class="label label-default bet-label <% if !@is_winner_bet_score.nil? %>green white-text<% end %>"><img class="z-depth-3" src=""><span class="winner-team-name"></span></p></div><div class="edit-bet-icon winner"><% if @winner_bet_deadline_time.future?%><i class="material-icons">edit</i><% else %>' + displayAllBetsHtml + '<%end%></div>';      
        </script>
        </form>
      </div>
    </div>
  </div>   
    
  </div>


</div>


<div class="row">
  <div class="col s12">
    <ul class="tabs blue-grey-text">
      <li class="tab col s3"><a class="blue-grey-text" href="#live"><%= t('live_games') %></a></li>
      <li class="tab col s3"><a class="active blue-grey-text" href="#incomming" ><%= t('incomming') %></a></li>
      <li class="tab col s3"><a class="blue-grey-text" href="#completed"><%= t('completed') %></a></li>
    </ul>
  </div>
</div>
<div class="row">
  <div class="col s12" id="live">
    <% if @live_games.empty? %>
      <%= render partial: "layouts/empty" %>
    <% else %>
      <% @live_games.each do |game| %>
        <%= render partial: "games/show_tile", locals: {game: game, bet: game.bet_for_user(current_user), comp: @competition} %>
      <% end %>
    <% end %>
  </div>
  
  
  <div class="col s12" id="incomming">     

  <% if @competition.event.games.incomming.empty? %>
      <%= render partial: "layouts/empty" %>
    <% else %>     
      <% @competition.event.games.incomming.group_by(&:day).each do |day, games| %>
        <div class="divider"></div>
        <div class="section">
        <h4><%= games.first.game_day %></h4>
        <% games.each do |game| %> 
          <%= render partial: "games/show_tile", locals: {game: game, bet: game.bet_for_user(current_user), comp: @competition} %>
        <% end %>
        </div>
      <% end %> 
    <% end %>
  </div>

  <div class="col s12" id="completed">
    <% if @completed_games.empty? %>
      <div class="col s12 center">
        <%= render partial: "layouts/empty" %>
      </div>
      <% else %>
        <% @completed_games.order("start_date DESC").group_by(&:day).each do |day, games| %>
          <div class="divider"></div>
          <div class="section">     
            <h4><%= games.first.game_day %></h4>
          <% games.each do |game| %> 
            <%= render partial: "games/show_tile", locals: {game: game, bet: game.bet_for_user(current_user), comp: @competition} %>
          <% end %>
          </div>
        <% end %> 
      <% end %>
  </div>
</div>

<div class="fixed-action-btn horizontal scale-transition scale-in tooltipped" data-position="left" data-delay="100" data-tooltip="Aktualne wyniki" style="bottom: 45px; right: 24px;">
  <%= link_to competition_results_path(@competition), class: "btn-floating btn-large amber" do %>
    <i class="large material-icons">insert_chart</i>
  <% end %> 
</div>

  <div id="allBetsModal" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h5> Typy wszystkich uczestników</h5>
      <separator>
      <div id="modalContent">
      </div>
    </div>
    <div class="modal-footer">
      <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat"><%= t('close') %></a>
    </div>
  </div>
<script>
(function($){
	$( document ).ready(function() {
        $('.bet-container').each(function() {
            $(this).displayBet();
        });
        $('#winner-bet').displayWinnerBet();
        $('.dropdown-button').dropdown();      
        $('select').material_select();  
        $(".button-collapse").sideNav({menuWidth: 320, activationWidth: 70, edge: 'right'});
        $('.modal-trigger').leanModal();          
        $('#messages').on('click', 'a', function(){
            $(this).closest('li').remove();
        });
        setIntervalAndExecute(function() {
		    $('#incomming .game-time').each(function() {
	        	var startTime = new Date(parseInt($(this).parent().find('input[name=game-time]').val()));
	        	var timeDifference = startTime.getTime() - new Date();
	        	if (timeDifference < 2 * 60 * 60 * 1000 && timeDifference > 0) {
	        		$(this).countdown({until: startTime, compact: true, onExpiry: function() {moveGameToLive($(this).parents('.match-row'));}});
	        	} else if (timeDifference <= 0) {
	        		moveGameToLive($(this).parents('.match-row'));
	        	}
	        });
        	var winnerStartTime = new Date(parseInt($('#winner-bet-form input[name=deadline]').val()));
        	var winnerTimeDifference = winnerStartTime.getTime() - new Date();
        	if (winnerTimeDifference < 2 * 60 * 60 * 1000 && winnerTimeDifference > 0) {
        		$('#winner-deadline').countdown({until: winnerStartTime, compact: true, onExpiry: function() {$('#winner-bet').disableWinnerBet();}});
        	} else if (winnerTimeDifference <= 0) {
        		$('#winner-bet').disableWinnerBet();
        	}
		}, 60 * 1000);
        Materialize.showStaggeredList('#results');
        $('html').bind("click touchend", function() {
        	$('.bet-container').each(function() {
	            $(this).displayBet();
	        });
	        if ($('#winner-bet input.select-dropdown').length > 0) {
	        	$('#winner-bet').displayWinnerBet();
	        }
        });
    });
})(jQuery);
</script>