config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :bets
      resources :competitions
      resources :competitions_users
      resources :events
      resources :games
      resources :teams

      root to: "users#index"
    end
  resources :bets

  resources :competitions

  resources :events

  resources :games

  resources :teams

  get 'competitions/:id/results' => 'competitions#results', :as => :competition_results
  get 'competitions/:id/join' => 'competitions#join', :as => :competition_join
  post 'competitions/:id/add_user' => 'competitions#add_user', :as => :competition_add_user
  delete 'competitions/:id/remove_user' => 'competitions#remove_user', :as => :competition_remove_user
  get 'games/:id/all_bets/:idc' => 'games#all_bets', :as => :games_all_bets
  get 'competition/:id/all_winner_bets/:idc' => 'competitions#all_winner_bets', :as => :competition_all_winner_bets

authenticated :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "visitors#index", :as => "authenticated_root"
end

devise_scope :user do
  root to: 'devise/sessions#new'
end
  devise_for :users	
  
  resources :users
end

app/models/bet.rb
class Bet < ActiveRecord::Base
  belongs_to :game
  belongs_to :competition
  belongs_to :owner, class_name: "User"

  #means that for one owner in one competition there can be only one bet of the given game
  # TODO: think if this could not be handled elsewhere
  validates_uniqueness_of :game, scope: [:owner,:competition]

  scope :for_user_and_competition, lambda { |usr,competition|
  	where(owner: usr, competition: competition)
  }
  scope :for_competition, lambda{ |competition|
    where(competition: competition)
  }

  validate :winner_bet_cannot_be_added_after_competition_start

  def winner_bet_cannot_be_added_after_competition_start
    errors.add("Wydarzenie już sie rozpoczelo") if
      game.nil? and competition.event.winner_bet_deadline_time < Time.zone.now
  end

  def is_editable?
  	if (game.nil?) #bet is for the whole competition
  		competition.event.start_date.nil? || competition.event.start_date > Time.zone.now ? true : false
  	else 
  		game.start_date > Time.zone.now ? true : false
  	end
  end

  def validate_result(actual_home_score, actual_away_score)
    if (actual_away_score == self.away_score && actual_home_score == self.home_score)
      # dokladny wynik trafiony
      self.points_earned = 3
    elsif (actual_home_score == actual_away_score && self.home_score == self.away_score) ||
        (actual_home_score < actual_away_score && self.home_score < self.away_score) ||
        (actual_home_score > actual_away_score && self.home_score > self.away_score)
      # trafione rozstrzygniecie
      self.points_earned = 1
    else
      self.points_earned = 0
    end
    self.update_attribute(:points_earned, self.points_earned)
  end
end

app/controllers/admin/bets_controller.rb
module Admin
  class BetsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/bets_controller.rb
class BetsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_bet, only: [:show, :edit, :update, :destroy]

  respond_to :json

  def index
    @bets = Bet.all.where(owner: current_user)
    respond_to do |format|
      format.html
    end
  end

  def show
    respond_to do |format|
      format.html
    end
  end

  def new
    @bet = Bet.new
    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    begin
      @bet = Bet.new(bet_params)
      @bet.owner_id = current_user.id
      #flash[:notice] = 'Bet was successfully created.' if 
      @bet.save
      respond_with(@bet)
    rescue
      return head(:internal_server_error)
    end
  end

  def update
    begin
      if (@bet.is_editable?)
        #flash[:notice] = 'Bet was successfully updated.' if 
        @bet.update(bet_params)
        respond_with(@bet)
      else 
        return head(:bad_request)
      end
    rescue
      return head(:internal_server_error)
    end
  end

  def destroy
    @bet.destroy
    respond_with(@bet)
  end

  private
    def set_bet
      @bet = Bet.find(params[:id])
    end

    def bet_params
      params.require(:bet).permit(:game_id, :competition_id, :home_score, :away_score, :advancing_team)
    end
end

app/helpers/bets_helper.rb
module BetsHelper
end

app/views/bets/_form.html.erb
<%= simple_form_for(@bet) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :game %>
    <%= f.association :competition %>
    <%= f.input :home_score %>
    <%= f.input :away_score %>
    <%= f.input :advancing_team %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/bets/edit.html.erb
<h1>Editing bet</h1>

<%= render 'form' %>

<%= link_to 'Show', @bet %> |
<%= link_to 'Back', bets_path %>

app/views/bets/index.html.erb
<h1>Listing bets</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Competition</th>
      <th>Owner</th>
      <th>Home score</th>
      <th>Away score</th>
      <th>Advancing team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bets.each do |bet| %>
      <tr>
        <td><%= bet.game_id %></td>
        <td><%= bet.competition_id %></td>
        <td><%= bet.owner_id %></td>
        <td><%= bet.home_score %></td>
        <td><%= bet.away_score %></td>
        <td><%= bet.advancing_team %></td>
        <td><%= link_to 'Show', bet %></td>
        <td><%= link_to 'Edit', edit_bet_path(bet) %></td>
        <td><%= link_to 'Destroy', bet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bet', new_bet_path %>

app/views/bets/new.html.erb
<h1>New bet</h1>

<%= render 'form' %>

<%= link_to 'Back', bets_path %>

app/views/bets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @bet.game_id %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @bet.competition_id %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @bet.owner_id %>
</p>

<p>
  <strong>Home score:</strong>
  <%= @bet.home_score %>
</p>

<p>
  <strong>Away score:</strong>
  <%= @bet.away_score %>
</p>

<p>
  <strong>Advancing team:</strong>
  <%= @bet.advancing_team %>
</p>

<%= link_to 'Edit', edit_bet_path(@bet) %> |
<%= link_to 'Back', bets_path %>