config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :bets
      resources :competitions
      resources :competitions_users
      resources :events
      resources :games
      resources :teams

      root to: "users#index"
    end
  resources :bets

  resources :competitions

  resources :events

  resources :games

  resources :teams

  get 'competitions/:id/results' => 'competitions#results', :as => :competition_results
  get 'competitions/:id/join' => 'competitions#join', :as => :competition_join
  post 'competitions/:id/add_user' => 'competitions#add_user', :as => :competition_add_user
  delete 'competitions/:id/remove_user' => 'competitions#remove_user', :as => :competition_remove_user
  get 'games/:id/all_bets/:idc' => 'games#all_bets', :as => :games_all_bets
  get 'competition/:id/all_winner_bets/:idc' => 'competitions#all_winner_bets', :as => :competition_all_winner_bets

authenticated :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "visitors#index", :as => "authenticated_root"
end

devise_scope :user do
  root to: 'devise/sessions#new'
end
  devise_for :users	
  
  resources :users
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_many :games
	has_many :competition
	has_many :teams, :through => :games, :source => :home_team
	belongs_to :creator, class_name: "User"
	has_attached_file :logo, :styles => { :small => "150x150>" }

	#validates_attachment_presence :logo
	validates_attachment_size :logo, :less_than => 2.megabytes
	validates_attachment_content_type :logo, :content_type => ['image/jpeg', 'image/png']

	def all_teams
		self.teams.uniq
	end

	
	def winner_bet_deadline_str
	  @bet_deadline = winner_bet_deadline_time
	  if (@bet_deadline.today?)
	    @bet_deadline.strftime("Dziś %H:%M")
	  elsif (@bet_deadline == Date.tomorrow)
	    @bet_deadline.strftime("Jutro %H:%M")
	  else
	    @bet_deadline.strftime("%F %H:%M")
	  end
	end
	
	def winner_bet_deadline_time
	  self.games.order('start_date ASC').first.start_date
	end
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @events = Event.all
    respond_with(@events)
  end

  def show
    respond_with(@event)
  end

  def new
    @event = Event.new
    respond_with(@event)
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.creator = current_user
    flash[:notice] = 'Event was successfully created.' if @event.save
    respond_with(@event)
  end

  def update
    flash[:notice] = 'Event was successfully updated.' if @event.update(event_params)
    respond_with(@event)
  end

  def destroy
    @event.destroy
    respond_with(@event)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:start_date, :name, :logo)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :start_date %>
    <%= f.input :name %>
    <%= f.file_field :logo %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<% content_for :welcome do %>
	 Wszystkie wydarzenia:
<% end %>
<ul class='collection'>
  <% @events.each do |event| %>
    <li class="collection-item">
      <div>
        <%= event.name %>
        <div class='secondary-content'>      
        <%= link_to event_path(event) do %>
            <i class="left-align material-icons">arrow_forward</i>
          <% end %>
          <%= link_to(event, method: :delete, data: { confirm: 'Are you sure?' }) do %>
            <i class="material-icons">cancel</i>
          <% end %>
        </div>
      </div>
    </li>
  <% end %>
</ul>
<br>
<% if can? :create, Event %>
  <%= link_to(new_event_path) do %>
    <button name='Stwórz nowe', class='btn waves-effect waves-light right-align'/>
  <% end %>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<h4>Mecze</h4>
 
<% @event.games.each do |game| %>
  <%= (render partial: 'games/show_basic', locals: { game: game } ) %>
<% end %> 

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>