config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :bets
      resources :competitions
      resources :competitions_users
      resources :events
      resources :games
      resources :teams

      root to: "users#index"
    end
  resources :bets

  resources :competitions

  resources :events

  resources :games

  resources :teams

  get 'competitions/:id/results' => 'competitions#results', :as => :competition_results
  get 'competitions/:id/join' => 'competitions#join', :as => :competition_join
  post 'competitions/:id/add_user' => 'competitions#add_user', :as => :competition_add_user
  delete 'competitions/:id/remove_user' => 'competitions#remove_user', :as => :competition_remove_user
  get 'games/:id/all_bets/:idc' => 'games#all_bets', :as => :games_all_bets
  get 'competition/:id/all_winner_bets/:idc' => 'competitions#all_winner_bets', :as => :competition_all_winner_bets

authenticated :user do
    # Rails 4 users must specify the 'as' option to give it a unique name
    root :to => "visitors#index", :as => "authenticated_root"
end

devise_scope :user do
  root to: 'devise/sessions#new'
end
  devise_for :users	
  
  resources :users
end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :event
	belongs_to :home_team, :class_name => "Team"
	belongs_to :away_team, :class_name => "Team"
	has_many :bets

	default_scope { order('start_date ASC') }

	scope :incomming, ->() { where("start_date > ?", Time.zone.now) }
	scope :live, ->() { where("start_date <= ? AND finish_date is NULL", Time.zone.now) }
	scope :completed, ->() { where("start_date < ? AND finish_date is not NULL", Time.zone.now).reorder('finish_date DESC') }

	after_update :update_related_bets

	def is_live 
		start_date <= Time.zone.now && finish_date.nil
	end

	def bet_for_user(user)
		self.bets.where(:owner => user)
	end

	def all_bets(competition)
		if (self.can_user_see_other_bets?)
			bets.for_competition(competition).group_by(&:owner).sort_by { |usr, bet|
			 bet.first.points_earned }.reverse
		end
	end

	def game_day
		if (self.start_date.today?) 
			"Dziś"
		elsif (self.start_date.to_date == Date.tomorrow)
			"Jutro"
		else
			I18n.l(self.start_date, format: :short)
		end
	end

	def day
		self.start_date.strftime('%D')
	end

	def is_bettable
		(self.home_team!=nil && self.away_team!=nil && self.start_date > Time.zone.now) ? true : false
	end

	def can_user_see_other_bets?
		self.start_date <= Time.zone.now ? true : false
	end

	protected 
		def update_related_bets
			logger.info "update requested"
			unless self.home_score == nil || self.away_score == nil
				logger.info "updating related bets"
				self.bets.each do |b|
					b.validate_result(self.home_score, self.away_score)	
				end
			end
		end
end

app/controllers/admin/games_controller.rb
module Admin
  class GamesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/games_controller.rb
 class GamesController < ApplicationController
  load_and_authorize_resource
  protect_from_forgery except: :all_bets
  before_action :authenticate_user!
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @games = Game.all
    respond_with(@games)
  end

  def show
    respond_with(@game)
  end

  def new
    @game = Game.new
    respond_with(@game)
  end

  def all_bets
    @bets = @game.all_bets(Competition.find params[:idc])
    respond_to do |format|
      format.js 
    end
  end

  def edit
    
  end

  def create
    @game = Game.new(game_params)
    flash[:notice] = 'Game was successfully created.' if @game.save
    respond_with(@game)
  end

  def update
    flash[:notice] = 'Game was successfully updated.' if @game.update(game_params)  
    redirect_to edit_game_path(@game)
  end

  def destroy
    @game.destroy
    respond_with(@game)
  end

  private
    def set_game
      @game = Game.find(params[:id])
    end

    def game_params
      params.require(:game).permit(:start_date, :finish_date, :home_team_id, :away_team_id, :event_id, :description, :home_score, :away_score)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_bets_list.html.erb
<ul class="collection with-header">
	<li class="collection-header">
		<br>
		<%= (render partial: 'show_basic', locals: { game: @game } ) %>
	</li>
	<% if @bets.empty? == false %>
	<% @bets.each do |user, bett| %>
	<% if user != nil %>
		<% if bett.first.points_earned == 3 %>
			<li class="collection-item green white-text">	    			
		<% elsif bett.first.points_earned == 1 %>
			<li class="collection-item blue white-text">
		<% else %>
			<li class="collection-item black-text">
		<% end %>
	    
    	<% if current_user==user %> <b> <% end %>
    	<%= user.name %>
    	<% if current_user==user %> </b> <% end %>
    	<span class="secondary-content bet-score">
    	 <% if bett.first.points_earned == 3 || bett.first.points_earned == 1 %>
    	 <span class="white-text">
    	 <% else %>
    	 <span class="black-text">
    	 <% end %>
    		<%= bett.first.home_score %> - <%= bett.first.away_score %>	    
    	</span>
    	</span>    	
	    </li>
	    <% end %>
	    <% end %>
	</ul>
	<% else %>
	</ul>
	<div class="center">
		<h5><%= t('none') %></h5>
	</div>
<% end %>

app/views/games/_form.html.erb
<%= simple_form_for(@game) do |f| %>
  <%= f.error_notification %>
    <div class="form-inputs">
    <%= f.association :event %>
      <div class="row">
        <div class='col s6'>
          <%= f.input :start_date, class: 'datepicker' %>
        </div>
        <div class='col s6'>
          <%= f.input :finish_date, class: 'datepicker' %>
        </div>
      </div>    
      <div class="row">
        <div class='col s6'>
          <%= f.association :home_team %>
          <br>
          <%= f.input :home_score %>
        </div>
        <div class='col s6'>
          <%= f.association :away_team %>
          <br>
          <%= f.input :away_score %> 
        </div>
      </div> <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, 'Aktualizuj' , class: 'btn waves-effect waves-light right-align', id: 'aktualizuj' %>
  </div>
<% end %>

app/views/games/_show_basic.html.erb
<div class="row">
   <div class="col s1 offset-s2 flag">
     <% if game.home_team != nil %>
      <% if game.home_team.national %>
          <%= image_tag game.home_team.flag.url(:tiny), :class => "z-depth-3" %>
        <% else %>
          <%= image_tag game.home_team.flag.url(:tiny) %>
        <% end %>
      <% else %>
        <%= image_tag "tiny/missing.png" %>
      <% end %>
    </div>
    <div class="col s2 left-align team-name">
    	<span class="game-team-home"><%= game.home_team!=nil ? game.home_team.name.mb_chars.upcase : "-" %></span>
    </div>
    <div class= "col s2 center-align score">  
      <span class="game-score"><%= game.home_score==nil || game.away_score == nil ? "TRWA" : game. home_score.to_s + ":" + game.away_score.to_s %></span>
      <!--<p class=""><%= game.game_group %>, <%= game.start_date %><p/>-->
    </div>
    <div class="col s2 right-align team-name">
    	<span class="game-team-away"><%= game.away_team!=nil ? game.away_team.name.mb_chars.upcase : "-" %></span>
    </div>
    <div class="col s2 flag"> 
      <% if game.away_team != nil %>
        <% if game.away_team.national %>  
          <%= image_tag game.away_team.flag.url(:tiny), :class => "z-depth-3" %>
        <% else %>
          <%= image_tag game.away_team.flag.url(:tiny) %>
        <% end %>
      <% else %>
        <%= image_tag "tiny/missing.png" %>
      <% end %>
      <% if current_user.admin? %>
      <%= link_to edit_game_path(game) do %>
        <i class="material-icons">edit</i>
      <% end %>
        
      <% end %>
    </div>
</div>

app/views/games/_show_tile.html.erb
<div class="row hoverable match-row">
  <div class="match-details row">
    <div class="col s2 match-additional-info">
	  <p><span class="title"><b><%= game.game_group %></b></span></p><p class="location"><%= game.location %>,<br><%= game.city%></p>
    </div>
    <div class="col s4 left-align home-team">
    	<div class="flag">
    	<% if game.home_team != nil %>
	      <% if game.home_team.national %>
	          <%= image_tag game.home_team.flag.url(:tiny), :class => "z-depth-3" %>
	      <% else %>
	          <%= image_tag game.home_team.flag.url(:tiny) %>
	      <% end %>
	    <% else %>
	      <%= image_tag "tiny/missing.png" %>
	    <% end %>
     	</div>
     	<div class="team-name">
      		<span><%= game.home_team!=nil ? game.home_team.name.mb_chars.upcase : "-" %></span>
    	</div>
    </div>
    <div class= "col s2 center-align score">
    	<input type="hidden" name="game-time" value="<%=game.start_date.strftime("%s000")%>"/>  
    	<% if game.start_date.past? %>
		  	<% if game.home_score==nil || game.away_score == nil %>
		  		<span class="game-score">TRWA</span>
		  	<% else %>
		  	    <span class="game-score"><%= game.home_score.to_s + ":" + game.away_score.to_s %></span>
		  	<% end %>
		<% else %>
			<span class="game-time"><%= game.start_date.strftime("%H:%M") %></span>
	  	<% end %>
    </div>
    <div class="col s4 right-align away-team">
    	<div class="flag">
	      <% if game.away_team != nil %>
	        <% if game.away_team.national %>
	          <%= image_tag game.away_team.flag.url(:tiny), :class => "z-depth-3" %>
	        <% else %>
	          <%= image_tag game.away_team.flag.url(:tiny) %>
	        <% end %>
	      <% else %>
	        <%= image_tag "tiny/missing.png" %>
	      <% end %>
        </div>
    	<div class="team-name">
      		<span><%= game.away_team!=nil ? game.away_team.name.mb_chars.upcase : "-" %></span>
      	</div>
    </div>
  </div>
  
  <div class="bet-details">
    <div class="game-bet">  
	  <% if game.home_team.nil? || game.away_team.nil? %>

      <% else %> 
      <form class="form-inline">
	      <input type="hidden" name="prev-bet-home" value="<%= bet[0] == nil ? '' : bet[0].home_score %>"/>
	      <input type="hidden" name="prev-bet-away" value="<%= bet[0] == nil ? '' : bet[0].away_score %>"/>
	      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
	      <input type="hidden" name="bet[game_id]" value="<%= game.id %>" />
	      <input type="hidden" name="bet[competition_id]" value="<%= params['id'] %>" />
	      <input type="hidden" name="bet_id" value="<%= bet[0] == nil ? '' : bet[0].id %>" />
	      <input type="hidden" name="bet_score" value="<%=bet[0] == nil ? '' : bet[0].points_earned%>" />
	      <input type="hidden" name="_method" value="post"/>
	      <div class="bet-container">
	      	<div class="display-all-bets-icon">
	      	<%= link_to games_all_bets_path(:id => game.id, :idc => comp.id, :format => "js"), :remote => true do %>
	      		<i class="material-icons">view_list</i>
	      	<% end %>
	      	</div>
	      </div>
	    </form>    
      <% end %>
    </div>
  </div>
  
</div>

app/views/games/all_bets.js.erb
$("#modalContent").html("<%= escape_javascript(render partial: 'bets_list', locals: { bets: @bets } ) %>"); 
$('#allBetsModal').openModal();

app/views/games/edit.html.erb
<% content_for :welcome do %>
	<%= t('game') %> <%= @game.id %> 
<% end %>
<%= render 'form' %>

app/views/games/index.html.erb
<% content_for :welcome do %>
  All games
<% end %>
<% @games.group_by(&:event).each do |event, games| %>
  <h3><%= event.name%></h3>
  <div class="tile-wrap">
    <% games.each do |game| %>
      <%= render partial: "games/show_tile", locals: {game: game, bet: game.bet_for_user(current_user), comp: @competition} %>
    <% end %>
  </div>
<% end %>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @game.start_date %>
</p>

<p>
  <strong>Finish date:</strong>
  <%= @game.finish_date %>
</p>

<p>
  <strong>Home team:</strong>
  <%= @game.home_team_id %>
</p>

<p>
  <strong>Away team:</strong>
  <%= @game.away_team_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>